#pragma once

#define YTD_APP_VERSION_MAJOR 1
#define YTD_APP_VERSION_MINOR 0
#define YTD_APP_VERSION_PATCH 3
#define YTD_APP_VERSION_BUILD 0

#define YTD_APP_VERSION_STRING "1.0.3"
#define YTD_APP_VERSION_WIDE L"1.0.3"
#define YTD_APP_FILE_VERSION_STRING "1.0.3.0"
#define YTD_APP_FILE_VERSION_RC 1,0,3,0
